/********************************************************************************
** Form generated from reading UI file 'window3.ui'
**
** Created by: Qt User Interface Compiler version 6.2.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINDOW3_H
#define UI_WINDOW3_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_window3
{
public:
    QPushButton *pushButton_delete;
    QPushButton *pushButton_check;
    QPushButton *pushButton20;
    QPushButton *pushButton11;
    QPushButton *pushButton22;
    QPushButton *pushButton02;
    QPushButton *pushButton10;
    QPushButton *pushButton01;
    QPushButton *pushButton21;
    QPushButton *pushButton00;
    QPushButton *pushButton12;
    QPushButton *pushButton_103;
    QPushButton *pushButton_101;
    QPushButton *pushButton_100;
    QPushButton *pushButton_102;
    QPushButton *pushButton_104;
    QPushButton *pushButton_105;
    QPushButton *pushButton_106;
    QPushButton *pushButton_108;
    QPushButton *pushButton_107;
    QPushButton *pushButton_118;
    QPushButton *pushButton_119;
    QPushButton *pushButton_122;
    QPushButton *pushButton_120;
    QPushButton *pushButton_121;
    QPushButton *pushButton_123;
    QPushButton *pushButton_124;
    QPushButton *pushButton_126;
    QPushButton *pushButton_125;
    QPushButton *pushButton_117;
    QPushButton *pushButton_115;
    QPushButton *pushButton_114;
    QPushButton *pushButton_116;
    QPushButton *pushButton_111;
    QPushButton *pushButton_109;
    QPushButton *pushButton_110;
    QPushButton *pushButton_112;
    QPushButton *pushButton_113;
    QPushButton *pushButton_93;
    QPushButton *pushButton_94;
    QPushButton *pushButton_92;
    QPushButton *pushButton_91;
    QPushButton *pushButton_95;
    QPushButton *pushButton_96;
    QPushButton *pushButton_98;
    QPushButton *pushButton_97;
    QPushButton *pushButton_99;
    QPushButton *pushButton_83;
    QPushButton *pushButton_82;
    QPushButton *pushButton_85;
    QPushButton *pushButton_86;
    QPushButton *pushButton_84;
    QPushButton *pushButton_87;
    QPushButton *pushButton_90;
    QPushButton *pushButton_88;
    QPushButton *pushButton_89;
    QPushButton *pushButton_53;
    QPushButton *pushButton_49;
    QPushButton *pushButton_55;
    QPushButton *pushButton_51;
    QPushButton *pushButton_48;
    QPushButton *pushButton_54;
    QPushButton *pushButton_50;
    QPushButton *pushButton_47;
    QPushButton *pushButton_52;
    QPushButton *pushButton_56;
    QPushButton *pushButton_46;
    QPushButton *pushButton_59;
    QPushButton *pushButton_58;
    QPushButton *pushButton_61;
    QPushButton *pushButton_60;
    QPushButton *pushButton_62;
    QPushButton *pushButton_57;
    QPushButton *pushButton_63;
    QPushButton *pushButton_74;
    QPushButton *pushButton_76;
    QPushButton *pushButton_73;
    QPushButton *pushButton_75;
    QPushButton *pushButton_77;
    QPushButton *pushButton_78;
    QPushButton *pushButton_81;
    QPushButton *pushButton_79;
    QPushButton *pushButton_80;
    QLabel *label;
    QPushButton *pushButton_num4;
    QPushButton *pushButton_num8;
    QPushButton *pushButton_num9;
    QPushButton *pushButton_num1;
    QPushButton *pushButton_num7;
    QPushButton *pushButton_num5;
    QPushButton *pushButton_num6;
    QPushButton *pushButton_num2;
    QPushButton *pushButton_num3;
    QFrame *frame;
    QLabel *label_2;

    void setupUi(QDialog *window3)
    {
        if (window3->objectName().isEmpty())
            window3->setObjectName(QString::fromUtf8("window3"));
        window3->resize(1000, 800);
        window3->setStyleSheet(QString::fromUtf8("QDialog{\n"
"	background: rgb(187, 255, 144);\n"
"}\n"
"QLabel{\n"
"	font-size: 35px;\n"
"	font-style: bold;\n"
"	\n"
"}\n"
"QPushButton{\n"
"	background: rgb(255, 255, 255);\n"
"	border: rgb(167, 255, 166);\n"
"	 \n"
"}"));
        pushButton_delete = new QPushButton(window3);
        pushButton_delete->setObjectName(QString::fromUtf8("pushButton_delete"));
        pushButton_delete->setGeometry(QRect(696, 286, 261, 61));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(pushButton_delete->sizePolicy().hasHeightForWidth());
        pushButton_delete->setSizePolicy(sizePolicy);
        QFont font;
        font.setPointSize(18);
        pushButton_delete->setFont(font);
        pushButton_delete->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(255, 51, 51);\n"
"}"));
        pushButton_check = new QPushButton(window3);
        pushButton_check->setObjectName(QString::fromUtf8("pushButton_check"));
        pushButton_check->setGeometry(QRect(696, 216, 261, 61));
        sizePolicy.setHeightForWidth(pushButton_check->sizePolicy().hasHeightForWidth());
        pushButton_check->setSizePolicy(sizePolicy);
        pushButton_check->setFont(font);
        pushButton_check->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(255, 255, 127);\n"
"}\n"
""));
        pushButton20 = new QPushButton(window3);
        pushButton20->setObjectName(QString::fromUtf8("pushButton20"));
        pushButton20->setGeometry(QRect(54, 282, 66, 63));
        sizePolicy.setHeightForWidth(pushButton20->sizePolicy().hasHeightForWidth());
        pushButton20->setSizePolicy(sizePolicy);
        pushButton20->setFont(font);
        pushButton11 = new QPushButton(window3);
        pushButton11->setObjectName(QString::fromUtf8("pushButton11"));
        pushButton11->setGeometry(QRect(120, 218, 66, 64));
        sizePolicy.setHeightForWidth(pushButton11->sizePolicy().hasHeightForWidth());
        pushButton11->setSizePolicy(sizePolicy);
        pushButton11->setFont(font);
        pushButton22 = new QPushButton(window3);
        pushButton22->setObjectName(QString::fromUtf8("pushButton22"));
        pushButton22->setGeometry(QRect(186, 282, 65, 63));
        sizePolicy.setHeightForWidth(pushButton22->sizePolicy().hasHeightForWidth());
        pushButton22->setSizePolicy(sizePolicy);
        pushButton22->setFont(font);
        pushButton02 = new QPushButton(window3);
        pushButton02->setObjectName(QString::fromUtf8("pushButton02"));
        pushButton02->setGeometry(QRect(186, 155, 65, 63));
        sizePolicy.setHeightForWidth(pushButton02->sizePolicy().hasHeightForWidth());
        pushButton02->setSizePolicy(sizePolicy);
        pushButton02->setFont(font);
        pushButton10 = new QPushButton(window3);
        pushButton10->setObjectName(QString::fromUtf8("pushButton10"));
        pushButton10->setGeometry(QRect(54, 218, 66, 64));
        sizePolicy.setHeightForWidth(pushButton10->sizePolicy().hasHeightForWidth());
        pushButton10->setSizePolicy(sizePolicy);
        pushButton10->setFont(font);
        pushButton01 = new QPushButton(window3);
        pushButton01->setObjectName(QString::fromUtf8("pushButton01"));
        pushButton01->setGeometry(QRect(120, 155, 66, 63));
        sizePolicy.setHeightForWidth(pushButton01->sizePolicy().hasHeightForWidth());
        pushButton01->setSizePolicy(sizePolicy);
        pushButton01->setFont(font);
        pushButton21 = new QPushButton(window3);
        pushButton21->setObjectName(QString::fromUtf8("pushButton21"));
        pushButton21->setGeometry(QRect(120, 282, 66, 63));
        sizePolicy.setHeightForWidth(pushButton21->sizePolicy().hasHeightForWidth());
        pushButton21->setSizePolicy(sizePolicy);
        pushButton21->setFont(font);
        pushButton00 = new QPushButton(window3);
        pushButton00->setObjectName(QString::fromUtf8("pushButton00"));
        pushButton00->setGeometry(QRect(54, 155, 66, 63));
        sizePolicy.setHeightForWidth(pushButton00->sizePolicy().hasHeightForWidth());
        pushButton00->setSizePolicy(sizePolicy);
        pushButton00->setFont(font);
        pushButton12 = new QPushButton(window3);
        pushButton12->setObjectName(QString::fromUtf8("pushButton12"));
        pushButton12->setGeometry(QRect(186, 218, 65, 64));
        sizePolicy.setHeightForWidth(pushButton12->sizePolicy().hasHeightForWidth());
        pushButton12->setSizePolicy(sizePolicy);
        pushButton12->setFont(font);
        pushButton_103 = new QPushButton(window3);
        pushButton_103->setObjectName(QString::fromUtf8("pushButton_103"));
        pushButton_103->setGeometry(QRect(465, 417, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_103->sizePolicy().hasHeightForWidth());
        pushButton_103->setSizePolicy(sizePolicy);
        pushButton_103->setFont(font);
        pushButton_101 = new QPushButton(window3);
        pushButton_101->setObjectName(QString::fromUtf8("pushButton_101"));
        pushButton_101->setGeometry(QRect(531, 354, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_101->sizePolicy().hasHeightForWidth());
        pushButton_101->setSizePolicy(sizePolicy);
        pushButton_101->setFont(font);
        pushButton_100 = new QPushButton(window3);
        pushButton_100->setObjectName(QString::fromUtf8("pushButton_100"));
        pushButton_100->setGeometry(QRect(596, 354, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_100->sizePolicy().hasHeightForWidth());
        pushButton_100->setSizePolicy(sizePolicy);
        pushButton_100->setFont(font);
        pushButton_102 = new QPushButton(window3);
        pushButton_102->setObjectName(QString::fromUtf8("pushButton_102"));
        pushButton_102->setGeometry(QRect(465, 354, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_102->sizePolicy().hasHeightForWidth());
        pushButton_102->setSizePolicy(sizePolicy);
        pushButton_102->setFont(font);
        pushButton_104 = new QPushButton(window3);
        pushButton_104->setObjectName(QString::fromUtf8("pushButton_104"));
        pushButton_104->setGeometry(QRect(465, 480, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_104->sizePolicy().hasHeightForWidth());
        pushButton_104->setSizePolicy(sizePolicy);
        pushButton_104->setFont(font);
        pushButton_105 = new QPushButton(window3);
        pushButton_105->setObjectName(QString::fromUtf8("pushButton_105"));
        pushButton_105->setGeometry(QRect(531, 417, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_105->sizePolicy().hasHeightForWidth());
        pushButton_105->setSizePolicy(sizePolicy);
        pushButton_105->setFont(font);
        pushButton_106 = new QPushButton(window3);
        pushButton_106->setObjectName(QString::fromUtf8("pushButton_106"));
        pushButton_106->setGeometry(QRect(596, 417, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_106->sizePolicy().hasHeightForWidth());
        pushButton_106->setSizePolicy(sizePolicy);
        pushButton_106->setFont(font);
        pushButton_108 = new QPushButton(window3);
        pushButton_108->setObjectName(QString::fromUtf8("pushButton_108"));
        pushButton_108->setGeometry(QRect(596, 480, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_108->sizePolicy().hasHeightForWidth());
        pushButton_108->setSizePolicy(sizePolicy);
        pushButton_108->setFont(font);
        pushButton_107 = new QPushButton(window3);
        pushButton_107->setObjectName(QString::fromUtf8("pushButton_107"));
        pushButton_107->setGeometry(QRect(531, 480, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_107->sizePolicy().hasHeightForWidth());
        pushButton_107->setSizePolicy(sizePolicy);
        pushButton_107->setFont(font);
        pushButton_118 = new QPushButton(window3);
        pushButton_118->setObjectName(QString::fromUtf8("pushButton_118"));
        pushButton_118->setGeometry(QRect(596, 552, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_118->sizePolicy().hasHeightForWidth());
        pushButton_118->setSizePolicy(sizePolicy);
        pushButton_118->setFont(font);
        pushButton_119 = new QPushButton(window3);
        pushButton_119->setObjectName(QString::fromUtf8("pushButton_119"));
        pushButton_119->setGeometry(QRect(531, 552, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_119->sizePolicy().hasHeightForWidth());
        pushButton_119->setSizePolicy(sizePolicy);
        pushButton_119->setFont(font);
        pushButton_122 = new QPushButton(window3);
        pushButton_122->setObjectName(QString::fromUtf8("pushButton_122"));
        pushButton_122->setGeometry(QRect(465, 679, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_122->sizePolicy().hasHeightForWidth());
        pushButton_122->setSizePolicy(sizePolicy);
        pushButton_122->setFont(font);
        pushButton_120 = new QPushButton(window3);
        pushButton_120->setObjectName(QString::fromUtf8("pushButton_120"));
        pushButton_120->setGeometry(QRect(465, 552, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_120->sizePolicy().hasHeightForWidth());
        pushButton_120->setSizePolicy(sizePolicy);
        pushButton_120->setFont(font);
        pushButton_121 = new QPushButton(window3);
        pushButton_121->setObjectName(QString::fromUtf8("pushButton_121"));
        pushButton_121->setGeometry(QRect(465, 615, 66, 64));
        sizePolicy.setHeightForWidth(pushButton_121->sizePolicy().hasHeightForWidth());
        pushButton_121->setSizePolicy(sizePolicy);
        pushButton_121->setFont(font);
        pushButton_123 = new QPushButton(window3);
        pushButton_123->setObjectName(QString::fromUtf8("pushButton_123"));
        pushButton_123->setGeometry(QRect(531, 615, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_123->sizePolicy().hasHeightForWidth());
        pushButton_123->setSizePolicy(sizePolicy);
        pushButton_123->setFont(font);
        pushButton_124 = new QPushButton(window3);
        pushButton_124->setObjectName(QString::fromUtf8("pushButton_124"));
        pushButton_124->setGeometry(QRect(596, 615, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_124->sizePolicy().hasHeightForWidth());
        pushButton_124->setSizePolicy(sizePolicy);
        pushButton_124->setFont(font);
        pushButton_126 = new QPushButton(window3);
        pushButton_126->setObjectName(QString::fromUtf8("pushButton_126"));
        pushButton_126->setGeometry(QRect(596, 679, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_126->sizePolicy().hasHeightForWidth());
        pushButton_126->setSizePolicy(sizePolicy);
        pushButton_126->setFont(font);
        pushButton_125 = new QPushButton(window3);
        pushButton_125->setObjectName(QString::fromUtf8("pushButton_125"));
        pushButton_125->setGeometry(QRect(531, 679, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_125->sizePolicy().hasHeightForWidth());
        pushButton_125->setSizePolicy(sizePolicy);
        pushButton_125->setFont(font);
        pushButton_117 = new QPushButton(window3);
        pushButton_117->setObjectName(QString::fromUtf8("pushButton_117"));
        pushButton_117->setGeometry(QRect(391, 679, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_117->sizePolicy().hasHeightForWidth());
        pushButton_117->setSizePolicy(sizePolicy);
        pushButton_117->setFont(font);
        pushButton_115 = new QPushButton(window3);
        pushButton_115->setObjectName(QString::fromUtf8("pushButton_115"));
        pushButton_115->setGeometry(QRect(391, 615, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_115->sizePolicy().hasHeightForWidth());
        pushButton_115->setSizePolicy(sizePolicy);
        pushButton_115->setFont(font);
        pushButton_114 = new QPushButton(window3);
        pushButton_114->setObjectName(QString::fromUtf8("pushButton_114"));
        pushButton_114->setGeometry(QRect(326, 615, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_114->sizePolicy().hasHeightForWidth());
        pushButton_114->setSizePolicy(sizePolicy);
        pushButton_114->setFont(font);
        pushButton_116 = new QPushButton(window3);
        pushButton_116->setObjectName(QString::fromUtf8("pushButton_116"));
        pushButton_116->setGeometry(QRect(326, 679, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_116->sizePolicy().hasHeightForWidth());
        pushButton_116->setSizePolicy(sizePolicy);
        pushButton_116->setFont(font);
        pushButton_111 = new QPushButton(window3);
        pushButton_111->setObjectName(QString::fromUtf8("pushButton_111"));
        pushButton_111->setGeometry(QRect(260, 552, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_111->sizePolicy().hasHeightForWidth());
        pushButton_111->setSizePolicy(sizePolicy);
        pushButton_111->setFont(font);
        pushButton_109 = new QPushButton(window3);
        pushButton_109->setObjectName(QString::fromUtf8("pushButton_109"));
        pushButton_109->setGeometry(QRect(391, 552, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_109->sizePolicy().hasHeightForWidth());
        pushButton_109->setSizePolicy(sizePolicy);
        pushButton_109->setFont(font);
        pushButton_110 = new QPushButton(window3);
        pushButton_110->setObjectName(QString::fromUtf8("pushButton_110"));
        pushButton_110->setGeometry(QRect(326, 552, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_110->sizePolicy().hasHeightForWidth());
        pushButton_110->setSizePolicy(sizePolicy);
        pushButton_110->setFont(font);
        pushButton_112 = new QPushButton(window3);
        pushButton_112->setObjectName(QString::fromUtf8("pushButton_112"));
        pushButton_112->setGeometry(QRect(260, 615, 66, 64));
        sizePolicy.setHeightForWidth(pushButton_112->sizePolicy().hasHeightForWidth());
        pushButton_112->setSizePolicy(sizePolicy);
        pushButton_112->setFont(font);
        pushButton_113 = new QPushButton(window3);
        pushButton_113->setObjectName(QString::fromUtf8("pushButton_113"));
        pushButton_113->setGeometry(QRect(260, 679, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_113->sizePolicy().hasHeightForWidth());
        pushButton_113->setSizePolicy(sizePolicy);
        pushButton_113->setFont(font);
        pushButton_93 = new QPushButton(window3);
        pushButton_93->setObjectName(QString::fromUtf8("pushButton_93"));
        pushButton_93->setGeometry(QRect(260, 354, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_93->sizePolicy().hasHeightForWidth());
        pushButton_93->setSizePolicy(sizePolicy);
        pushButton_93->setFont(font);
        pushButton_94 = new QPushButton(window3);
        pushButton_94->setObjectName(QString::fromUtf8("pushButton_94"));
        pushButton_94->setGeometry(QRect(260, 417, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_94->sizePolicy().hasHeightForWidth());
        pushButton_94->setSizePolicy(sizePolicy);
        pushButton_94->setFont(font);
        pushButton_92 = new QPushButton(window3);
        pushButton_92->setObjectName(QString::fromUtf8("pushButton_92"));
        pushButton_92->setGeometry(QRect(326, 354, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_92->sizePolicy().hasHeightForWidth());
        pushButton_92->setSizePolicy(sizePolicy);
        pushButton_92->setFont(font);
        pushButton_91 = new QPushButton(window3);
        pushButton_91->setObjectName(QString::fromUtf8("pushButton_91"));
        pushButton_91->setGeometry(QRect(391, 354, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_91->sizePolicy().hasHeightForWidth());
        pushButton_91->setSizePolicy(sizePolicy);
        pushButton_91->setFont(font);
        pushButton_95 = new QPushButton(window3);
        pushButton_95->setObjectName(QString::fromUtf8("pushButton_95"));
        pushButton_95->setGeometry(QRect(260, 480, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_95->sizePolicy().hasHeightForWidth());
        pushButton_95->setSizePolicy(sizePolicy);
        pushButton_95->setFont(font);
        pushButton_96 = new QPushButton(window3);
        pushButton_96->setObjectName(QString::fromUtf8("pushButton_96"));
        pushButton_96->setGeometry(QRect(326, 417, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_96->sizePolicy().hasHeightForWidth());
        pushButton_96->setSizePolicy(sizePolicy);
        pushButton_96->setFont(font);
        pushButton_98 = new QPushButton(window3);
        pushButton_98->setObjectName(QString::fromUtf8("pushButton_98"));
        pushButton_98->setGeometry(QRect(326, 480, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_98->sizePolicy().hasHeightForWidth());
        pushButton_98->setSizePolicy(sizePolicy);
        pushButton_98->setFont(font);
        pushButton_97 = new QPushButton(window3);
        pushButton_97->setObjectName(QString::fromUtf8("pushButton_97"));
        pushButton_97->setGeometry(QRect(391, 417, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_97->sizePolicy().hasHeightForWidth());
        pushButton_97->setSizePolicy(sizePolicy);
        pushButton_97->setFont(font);
        pushButton_99 = new QPushButton(window3);
        pushButton_99->setObjectName(QString::fromUtf8("pushButton_99"));
        pushButton_99->setGeometry(QRect(391, 480, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_99->sizePolicy().hasHeightForWidth());
        pushButton_99->setSizePolicy(sizePolicy);
        pushButton_99->setFont(font);
        pushButton_83 = new QPushButton(window3);
        pushButton_83->setObjectName(QString::fromUtf8("pushButton_83"));
        pushButton_83->setGeometry(QRect(120, 552, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_83->sizePolicy().hasHeightForWidth());
        pushButton_83->setSizePolicy(sizePolicy);
        pushButton_83->setFont(font);
        pushButton_82 = new QPushButton(window3);
        pushButton_82->setObjectName(QString::fromUtf8("pushButton_82"));
        pushButton_82->setGeometry(QRect(186, 552, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_82->sizePolicy().hasHeightForWidth());
        pushButton_82->setSizePolicy(sizePolicy);
        pushButton_82->setFont(font);
        pushButton_85 = new QPushButton(window3);
        pushButton_85->setObjectName(QString::fromUtf8("pushButton_85"));
        pushButton_85->setGeometry(QRect(54, 615, 66, 64));
        sizePolicy.setHeightForWidth(pushButton_85->sizePolicy().hasHeightForWidth());
        pushButton_85->setSizePolicy(sizePolicy);
        pushButton_85->setFont(font);
        pushButton_86 = new QPushButton(window3);
        pushButton_86->setObjectName(QString::fromUtf8("pushButton_86"));
        pushButton_86->setGeometry(QRect(54, 679, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_86->sizePolicy().hasHeightForWidth());
        pushButton_86->setSizePolicy(sizePolicy);
        pushButton_86->setFont(font);
        pushButton_84 = new QPushButton(window3);
        pushButton_84->setObjectName(QString::fromUtf8("pushButton_84"));
        pushButton_84->setGeometry(QRect(54, 552, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_84->sizePolicy().hasHeightForWidth());
        pushButton_84->setSizePolicy(sizePolicy);
        pushButton_84->setFont(font);
        pushButton_87 = new QPushButton(window3);
        pushButton_87->setObjectName(QString::fromUtf8("pushButton_87"));
        pushButton_87->setGeometry(QRect(120, 615, 66, 64));
        sizePolicy.setHeightForWidth(pushButton_87->sizePolicy().hasHeightForWidth());
        pushButton_87->setSizePolicy(sizePolicy);
        pushButton_87->setFont(font);
        pushButton_90 = new QPushButton(window3);
        pushButton_90->setObjectName(QString::fromUtf8("pushButton_90"));
        pushButton_90->setGeometry(QRect(186, 679, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_90->sizePolicy().hasHeightForWidth());
        pushButton_90->setSizePolicy(sizePolicy);
        pushButton_90->setFont(font);
        pushButton_88 = new QPushButton(window3);
        pushButton_88->setObjectName(QString::fromUtf8("pushButton_88"));
        pushButton_88->setGeometry(QRect(186, 615, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_88->sizePolicy().hasHeightForWidth());
        pushButton_88->setSizePolicy(sizePolicy);
        pushButton_88->setFont(font);
        pushButton_89 = new QPushButton(window3);
        pushButton_89->setObjectName(QString::fromUtf8("pushButton_89"));
        pushButton_89->setGeometry(QRect(120, 679, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_89->sizePolicy().hasHeightForWidth());
        pushButton_89->setSizePolicy(sizePolicy);
        pushButton_89->setFont(font);
        pushButton_53 = new QPushButton(window3);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(596, 218, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_53->sizePolicy().hasHeightForWidth());
        pushButton_53->setSizePolicy(sizePolicy);
        pushButton_53->setFont(font);
        pushButton_49 = new QPushButton(window3);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(465, 155, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_49->sizePolicy().hasHeightForWidth());
        pushButton_49->setSizePolicy(sizePolicy);
        pushButton_49->setFont(font);
        pushButton_55 = new QPushButton(window3);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(596, 282, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_55->sizePolicy().hasHeightForWidth());
        pushButton_55->setSizePolicy(sizePolicy);
        pushButton_55->setFont(font);
        pushButton_51 = new QPushButton(window3);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(465, 282, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_51->sizePolicy().hasHeightForWidth());
        pushButton_51->setSizePolicy(sizePolicy);
        pushButton_51->setFont(font);
        pushButton_48 = new QPushButton(window3);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(531, 155, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_48->sizePolicy().hasHeightForWidth());
        pushButton_48->setSizePolicy(sizePolicy);
        pushButton_48->setFont(font);
        pushButton_54 = new QPushButton(window3);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(531, 282, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_54->sizePolicy().hasHeightForWidth());
        pushButton_54->setSizePolicy(sizePolicy);
        pushButton_54->setFont(font);
        pushButton_50 = new QPushButton(window3);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(465, 218, 66, 64));
        sizePolicy.setHeightForWidth(pushButton_50->sizePolicy().hasHeightForWidth());
        pushButton_50->setSizePolicy(sizePolicy);
        pushButton_50->setFont(font);
        pushButton_47 = new QPushButton(window3);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(596, 155, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_47->sizePolicy().hasHeightForWidth());
        pushButton_47->setSizePolicy(sizePolicy);
        pushButton_47->setFont(font);
        pushButton_52 = new QPushButton(window3);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(531, 218, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_52->sizePolicy().hasHeightForWidth());
        pushButton_52->setSizePolicy(sizePolicy);
        pushButton_52->setFont(font);
        pushButton_56 = new QPushButton(window3);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(326, 155, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_56->sizePolicy().hasHeightForWidth());
        pushButton_56->setSizePolicy(sizePolicy);
        pushButton_56->setFont(font);
        pushButton_46 = new QPushButton(window3);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(391, 155, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_46->sizePolicy().hasHeightForWidth());
        pushButton_46->setSizePolicy(sizePolicy);
        pushButton_46->setFont(font);
        pushButton_59 = new QPushButton(window3);
        pushButton_59->setObjectName(QString::fromUtf8("pushButton_59"));
        pushButton_59->setGeometry(QRect(260, 282, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_59->sizePolicy().hasHeightForWidth());
        pushButton_59->setSizePolicy(sizePolicy);
        pushButton_59->setFont(font);
        pushButton_58 = new QPushButton(window3);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(260, 218, 66, 64));
        sizePolicy.setHeightForWidth(pushButton_58->sizePolicy().hasHeightForWidth());
        pushButton_58->setSizePolicy(sizePolicy);
        pushButton_58->setFont(font);
        pushButton_61 = new QPushButton(window3);
        pushButton_61->setObjectName(QString::fromUtf8("pushButton_61"));
        pushButton_61->setGeometry(QRect(391, 218, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_61->sizePolicy().hasHeightForWidth());
        pushButton_61->setSizePolicy(sizePolicy);
        pushButton_61->setFont(font);
        pushButton_60 = new QPushButton(window3);
        pushButton_60->setObjectName(QString::fromUtf8("pushButton_60"));
        pushButton_60->setGeometry(QRect(326, 218, 65, 64));
        sizePolicy.setHeightForWidth(pushButton_60->sizePolicy().hasHeightForWidth());
        pushButton_60->setSizePolicy(sizePolicy);
        pushButton_60->setFont(font);
        pushButton_62 = new QPushButton(window3);
        pushButton_62->setObjectName(QString::fromUtf8("pushButton_62"));
        pushButton_62->setGeometry(QRect(326, 282, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_62->sizePolicy().hasHeightForWidth());
        pushButton_62->setSizePolicy(sizePolicy);
        pushButton_62->setFont(font);
        pushButton_57 = new QPushButton(window3);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(260, 155, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_57->sizePolicy().hasHeightForWidth());
        pushButton_57->setSizePolicy(sizePolicy);
        pushButton_57->setFont(font);
        pushButton_63 = new QPushButton(window3);
        pushButton_63->setObjectName(QString::fromUtf8("pushButton_63"));
        pushButton_63->setGeometry(QRect(391, 282, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_63->sizePolicy().hasHeightForWidth());
        pushButton_63->setSizePolicy(sizePolicy);
        pushButton_63->setFont(font);
        pushButton_74 = new QPushButton(window3);
        pushButton_74->setObjectName(QString::fromUtf8("pushButton_74"));
        pushButton_74->setGeometry(QRect(120, 354, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_74->sizePolicy().hasHeightForWidth());
        pushButton_74->setSizePolicy(sizePolicy);
        pushButton_74->setFont(font);
        pushButton_76 = new QPushButton(window3);
        pushButton_76->setObjectName(QString::fromUtf8("pushButton_76"));
        pushButton_76->setGeometry(QRect(54, 417, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_76->sizePolicy().hasHeightForWidth());
        pushButton_76->setSizePolicy(sizePolicy);
        pushButton_76->setFont(font);
        pushButton_73 = new QPushButton(window3);
        pushButton_73->setObjectName(QString::fromUtf8("pushButton_73"));
        pushButton_73->setGeometry(QRect(186, 354, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_73->sizePolicy().hasHeightForWidth());
        pushButton_73->setSizePolicy(sizePolicy);
        pushButton_73->setFont(font);
        pushButton_75 = new QPushButton(window3);
        pushButton_75->setObjectName(QString::fromUtf8("pushButton_75"));
        pushButton_75->setGeometry(QRect(54, 354, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_75->sizePolicy().hasHeightForWidth());
        pushButton_75->setSizePolicy(sizePolicy);
        pushButton_75->setFont(font);
        pushButton_77 = new QPushButton(window3);
        pushButton_77->setObjectName(QString::fromUtf8("pushButton_77"));
        pushButton_77->setGeometry(QRect(54, 480, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_77->sizePolicy().hasHeightForWidth());
        pushButton_77->setSizePolicy(sizePolicy);
        pushButton_77->setFont(font);
        pushButton_78 = new QPushButton(window3);
        pushButton_78->setObjectName(QString::fromUtf8("pushButton_78"));
        pushButton_78->setGeometry(QRect(120, 417, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_78->sizePolicy().hasHeightForWidth());
        pushButton_78->setSizePolicy(sizePolicy);
        pushButton_78->setFont(font);
        pushButton_81 = new QPushButton(window3);
        pushButton_81->setObjectName(QString::fromUtf8("pushButton_81"));
        pushButton_81->setGeometry(QRect(186, 480, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_81->sizePolicy().hasHeightForWidth());
        pushButton_81->setSizePolicy(sizePolicy);
        pushButton_81->setFont(font);
        pushButton_79 = new QPushButton(window3);
        pushButton_79->setObjectName(QString::fromUtf8("pushButton_79"));
        pushButton_79->setGeometry(QRect(186, 417, 65, 63));
        sizePolicy.setHeightForWidth(pushButton_79->sizePolicy().hasHeightForWidth());
        pushButton_79->setSizePolicy(sizePolicy);
        pushButton_79->setFont(font);
        pushButton_80 = new QPushButton(window3);
        pushButton_80->setObjectName(QString::fromUtf8("pushButton_80"));
        pushButton_80->setGeometry(QRect(120, 480, 66, 63));
        sizePolicy.setHeightForWidth(pushButton_80->sizePolicy().hasHeightForWidth());
        pushButton_80->setSizePolicy(sizePolicy);
        pushButton_80->setFont(font);
        label = new QLabel(window3);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(300, 40, 391, 61));
        label->setStyleSheet(QString::fromUtf8("QLabel{\n"
"	color: rgb(85, 170, 255);\n"
"	font-family:  \"Broadway\";\n"
"	font-size: 50px;\n"
"}"));
        pushButton_num4 = new QPushButton(window3);
        pushButton_num4->setObjectName(QString::fromUtf8("pushButton_num4"));
        pushButton_num4->setGeometry(QRect(697, 443, 87, 87));
        sizePolicy.setHeightForWidth(pushButton_num4->sizePolicy().hasHeightForWidth());
        pushButton_num4->setSizePolicy(sizePolicy);
        pushButton_num4->setFont(font);
        pushButton_num4->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num8 = new QPushButton(window3);
        pushButton_num8->setObjectName(QString::fromUtf8("pushButton_num8"));
        pushButton_num8->setGeometry(QRect(784, 357, 86, 86));
        sizePolicy.setHeightForWidth(pushButton_num8->sizePolicy().hasHeightForWidth());
        pushButton_num8->setSizePolicy(sizePolicy);
        pushButton_num8->setFont(font);
        pushButton_num8->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num9 = new QPushButton(window3);
        pushButton_num9->setObjectName(QString::fromUtf8("pushButton_num9"));
        pushButton_num9->setGeometry(QRect(870, 357, 86, 86));
        sizePolicy.setHeightForWidth(pushButton_num9->sizePolicy().hasHeightForWidth());
        pushButton_num9->setSizePolicy(sizePolicy);
        pushButton_num9->setFont(font);
        pushButton_num9->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num1 = new QPushButton(window3);
        pushButton_num1->setObjectName(QString::fromUtf8("pushButton_num1"));
        pushButton_num1->setGeometry(QRect(697, 530, 87, 86));
        sizePolicy.setHeightForWidth(pushButton_num1->sizePolicy().hasHeightForWidth());
        pushButton_num1->setSizePolicy(sizePolicy);
        pushButton_num1->setFont(font);
        pushButton_num1->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num7 = new QPushButton(window3);
        pushButton_num7->setObjectName(QString::fromUtf8("pushButton_num7"));
        pushButton_num7->setGeometry(QRect(697, 357, 87, 86));
        sizePolicy.setHeightForWidth(pushButton_num7->sizePolicy().hasHeightForWidth());
        pushButton_num7->setSizePolicy(sizePolicy);
        pushButton_num7->setFont(font);
        pushButton_num7->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num5 = new QPushButton(window3);
        pushButton_num5->setObjectName(QString::fromUtf8("pushButton_num5"));
        pushButton_num5->setGeometry(QRect(784, 443, 86, 87));
        sizePolicy.setHeightForWidth(pushButton_num5->sizePolicy().hasHeightForWidth());
        pushButton_num5->setSizePolicy(sizePolicy);
        pushButton_num5->setFont(font);
        pushButton_num5->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num6 = new QPushButton(window3);
        pushButton_num6->setObjectName(QString::fromUtf8("pushButton_num6"));
        pushButton_num6->setGeometry(QRect(870, 443, 86, 87));
        sizePolicy.setHeightForWidth(pushButton_num6->sizePolicy().hasHeightForWidth());
        pushButton_num6->setSizePolicy(sizePolicy);
        pushButton_num6->setFont(font);
        pushButton_num6->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num2 = new QPushButton(window3);
        pushButton_num2->setObjectName(QString::fromUtf8("pushButton_num2"));
        pushButton_num2->setGeometry(QRect(784, 530, 86, 86));
        sizePolicy.setHeightForWidth(pushButton_num2->sizePolicy().hasHeightForWidth());
        pushButton_num2->setSizePolicy(sizePolicy);
        pushButton_num2->setFont(font);
        pushButton_num2->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        pushButton_num3 = new QPushButton(window3);
        pushButton_num3->setObjectName(QString::fromUtf8("pushButton_num3"));
        pushButton_num3->setGeometry(QRect(870, 530, 86, 86));
        sizePolicy.setHeightForWidth(pushButton_num3->sizePolicy().hasHeightForWidth());
        pushButton_num3->setSizePolicy(sizePolicy);
        pushButton_num3->setFont(font);
        pushButton_num3->setStyleSheet(QString::fromUtf8("QPushButton{\n"
"	background: rgb(75, 162, 255)\n"
"}"));
        frame = new QFrame(window3);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(40, 140, 635, 616));
        frame->setStyleSheet(QString::fromUtf8("QFrame{\n"
"	background: rgb(85, 85, 255);\n"
"}"));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label_2 = new QLabel(window3);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(310, 50, 391, 61));
        label_2->setStyleSheet(QString::fromUtf8("QLabel{\n"
"	color: rgb(0, 85, 255);\n"
"	font-family:  \"Broadway\";\n"
"	font-size: 50px;\n"
"}"));
        frame->raise();
        pushButton_delete->raise();
        pushButton_check->raise();
        pushButton20->raise();
        pushButton11->raise();
        pushButton22->raise();
        pushButton02->raise();
        pushButton10->raise();
        pushButton01->raise();
        pushButton21->raise();
        pushButton00->raise();
        pushButton12->raise();
        pushButton_103->raise();
        pushButton_101->raise();
        pushButton_100->raise();
        pushButton_102->raise();
        pushButton_104->raise();
        pushButton_105->raise();
        pushButton_106->raise();
        pushButton_108->raise();
        pushButton_107->raise();
        pushButton_118->raise();
        pushButton_119->raise();
        pushButton_122->raise();
        pushButton_120->raise();
        pushButton_121->raise();
        pushButton_123->raise();
        pushButton_124->raise();
        pushButton_126->raise();
        pushButton_125->raise();
        pushButton_117->raise();
        pushButton_115->raise();
        pushButton_114->raise();
        pushButton_116->raise();
        pushButton_111->raise();
        pushButton_109->raise();
        pushButton_110->raise();
        pushButton_112->raise();
        pushButton_113->raise();
        pushButton_93->raise();
        pushButton_94->raise();
        pushButton_92->raise();
        pushButton_91->raise();
        pushButton_95->raise();
        pushButton_96->raise();
        pushButton_98->raise();
        pushButton_97->raise();
        pushButton_99->raise();
        pushButton_83->raise();
        pushButton_82->raise();
        pushButton_85->raise();
        pushButton_86->raise();
        pushButton_84->raise();
        pushButton_87->raise();
        pushButton_90->raise();
        pushButton_88->raise();
        pushButton_89->raise();
        pushButton_53->raise();
        pushButton_49->raise();
        pushButton_55->raise();
        pushButton_51->raise();
        pushButton_48->raise();
        pushButton_54->raise();
        pushButton_50->raise();
        pushButton_47->raise();
        pushButton_52->raise();
        pushButton_56->raise();
        pushButton_46->raise();
        pushButton_59->raise();
        pushButton_58->raise();
        pushButton_61->raise();
        pushButton_60->raise();
        pushButton_62->raise();
        pushButton_57->raise();
        pushButton_63->raise();
        pushButton_74->raise();
        pushButton_76->raise();
        pushButton_73->raise();
        pushButton_75->raise();
        pushButton_77->raise();
        pushButton_78->raise();
        pushButton_81->raise();
        pushButton_79->raise();
        pushButton_80->raise();
        label->raise();
        pushButton_num4->raise();
        pushButton_num8->raise();
        pushButton_num9->raise();
        pushButton_num1->raise();
        pushButton_num7->raise();
        pushButton_num5->raise();
        pushButton_num6->raise();
        pushButton_num2->raise();
        pushButton_num3->raise();
        label_2->raise();

        retranslateUi(window3);

        QMetaObject::connectSlotsByName(window3);
    } // setupUi

    void retranslateUi(QDialog *window3)
    {
        window3->setWindowTitle(QCoreApplication::translate("window3", "Dialog", nullptr));
        pushButton_delete->setText(QCoreApplication::translate("window3", "DELETE", nullptr));
        pushButton_check->setText(QCoreApplication::translate("window3", "CHECK", nullptr));
        pushButton20->setText(QString());
        pushButton11->setText(QString());
        pushButton22->setText(QString());
        pushButton02->setText(QString());
        pushButton10->setText(QString());
        pushButton01->setText(QString());
        pushButton21->setText(QString());
        pushButton00->setText(QString());
        pushButton12->setText(QString());
        pushButton_103->setText(QString());
        pushButton_101->setText(QString());
        pushButton_100->setText(QString());
        pushButton_102->setText(QString());
        pushButton_104->setText(QString());
        pushButton_105->setText(QString());
        pushButton_106->setText(QString());
        pushButton_108->setText(QString());
        pushButton_107->setText(QString());
        pushButton_118->setText(QString());
        pushButton_119->setText(QString());
        pushButton_122->setText(QString());
        pushButton_120->setText(QString());
        pushButton_121->setText(QString());
        pushButton_123->setText(QString());
        pushButton_124->setText(QString());
        pushButton_126->setText(QString());
        pushButton_125->setText(QString());
        pushButton_117->setText(QString());
        pushButton_115->setText(QString());
        pushButton_114->setText(QString());
        pushButton_116->setText(QString());
        pushButton_111->setText(QString());
        pushButton_109->setText(QString());
        pushButton_110->setText(QString());
        pushButton_112->setText(QString());
        pushButton_113->setText(QString());
        pushButton_93->setText(QString());
        pushButton_94->setText(QString());
        pushButton_92->setText(QString());
        pushButton_91->setText(QString());
        pushButton_95->setText(QString());
        pushButton_96->setText(QString());
        pushButton_98->setText(QString());
        pushButton_97->setText(QString());
        pushButton_99->setText(QString());
        pushButton_83->setText(QString());
        pushButton_82->setText(QString());
        pushButton_85->setText(QString());
        pushButton_86->setText(QString());
        pushButton_84->setText(QString());
        pushButton_87->setText(QString());
        pushButton_90->setText(QString());
        pushButton_88->setText(QString());
        pushButton_89->setText(QString());
        pushButton_53->setText(QString());
        pushButton_49->setText(QString());
        pushButton_55->setText(QString());
        pushButton_51->setText(QString());
        pushButton_48->setText(QString());
        pushButton_54->setText(QString());
        pushButton_50->setText(QString());
        pushButton_47->setText(QString());
        pushButton_52->setText(QString());
        pushButton_56->setText(QString());
        pushButton_46->setText(QString());
        pushButton_59->setText(QString());
        pushButton_58->setText(QString());
        pushButton_61->setText(QString());
        pushButton_60->setText(QString());
        pushButton_62->setText(QString());
        pushButton_57->setText(QString());
        pushButton_63->setText(QString());
        pushButton_74->setText(QString());
        pushButton_76->setText(QString());
        pushButton_73->setText(QString());
        pushButton_75->setText(QString());
        pushButton_77->setText(QString());
        pushButton_78->setText(QString());
        pushButton_81->setText(QString());
        pushButton_79->setText(QString());
        pushButton_80->setText(QString());
        label->setText(QCoreApplication::translate("window3", "SUDOKU GAME", nullptr));
        pushButton_num4->setText(QCoreApplication::translate("window3", "4", nullptr));
        pushButton_num8->setText(QCoreApplication::translate("window3", "8", nullptr));
        pushButton_num9->setText(QCoreApplication::translate("window3", "9", nullptr));
        pushButton_num1->setText(QCoreApplication::translate("window3", "1", nullptr));
        pushButton_num7->setText(QCoreApplication::translate("window3", "7", nullptr));
        pushButton_num5->setText(QCoreApplication::translate("window3", "5", nullptr));
        pushButton_num6->setText(QCoreApplication::translate("window3", "6", nullptr));
        pushButton_num2->setText(QCoreApplication::translate("window3", "2", nullptr));
        pushButton_num3->setText(QCoreApplication::translate("window3", "3", nullptr));
        label_2->setText(QCoreApplication::translate("window3", "SUDOKU GAME", nullptr));
    } // retranslateUi

};

namespace Ui {
    class window3: public Ui_window3 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINDOW3_H
